const characters = {

    ye_lai_test:{
    sex:"male",
    group:"wei",
    hp:4,
    skills:["ye_skill"],
},
    feitiandahama:{
    sex:"male",
    group:"shen",
    hp:5,
    skills:[
        "ftdh_jiangshi",
        "ftdh_feiha",
        "ftdh_huawu"
    ]
    },
    xiongshixiansheng:{
    sex:"male",
    group:"qun",
    hp:5,
    skills:[
        "xs_luoshi",
        "xs_tanshi",
        "xs_wumou"
    ],
},
gongjiaoche_emo:{
    sex:"none",
    group:"shen",
    hp:5,
    skills:[
        "gjc_youhua",
        "gjc_shitong",
        "gjc_huawu"
    ],
},
laov:{
    sex:"male",
    group:"wei",
    hp:4,
    skills:[
        "lv_aichuan",
        "lv_kuangchuan",
        "lv_yiqichuan"
    ],
},
yingsanshi:{
    sex:"female",
    group:"shen",
    hp:3,
    skills:[
        "ys_dengji",
        "ys_feileishen",
        "ys_zhongmu",
        "ys_maomao",
        "ys_yelaifengyusheng"
    ],
},
sf:{
    sex:"male",
    group:"wei",
    hp:4,
    skills:[
        "sf_daguo",
        "sf_zhengdan",
        "sf_hongquan"
    ],
},
dongming:{
    sex:"female",
    group:"shu",
    hp:3,
    skills:[
        "dm_gaoshu",
        "dm_shishu",
        "dm_chibao"
    ],
},

};
	

export default characters;
