extension["夜来风雨声"]={
	intro:"",
	author:"无名玩家",
	netdisk:"",
	forum:"",
	version:"1.0",
	files:["info.json","README.md","飞天大蛤蟆.jpg","LICENSE","info.json","LICENSE","README.md","飞天大蛤蟆.jpg"],
	size:"1.5MB"
};